import { useEffect, useMemo, useState } from 'react';
import { Link, NavLink, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api';

function AdminShell({ title, eyebrow = 'VELORA STUDIO', children, actions }) {
  return <main className="admin-page"><div className="admin-top"><div><small>{eyebrow}</small><h1>{title}</h1></div>{actions}</div><nav className="admin-nav"><NavLink end to="/admin">Overview</NavLink><NavLink to="/admin/products">Products</NavLink><NavLink to="/admin/orders">Orders</NavLink><NavLink to="/admin/customers">Customers</NavLink><NavLink to="/admin/messages">Messages</NavLink></nav>{children}</main>;
}

export function AdminDashboard() {
  const [stats, setStats] = useState(null); const [orders, setOrders] = useState([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.adminStats(), api.adminOrders()]).then(([s, o]) => { setStats(s); setOrders(o.slice(0, 6)); }).catch((e) => setError(e.message)); }, []);
  return <AdminShell title="Admin overview">{error && <p className="auth-error">{error}</p>}{stats && <><div className="stats"><article><span>Revenue</span><b>${Math.round(stats.revenue)}</b></article><article><span>Orders</span><b>{stats.orders}</b></article><article><span>Customers</span><b>{stats.customers}</b></article><article><span>Inventory</span><b>{stats.inventory}</b></article></div><section className="admin-panel"><div className="admin-section-title"><h2>Recent orders</h2><Link to="/admin/orders">View all →</Link></div>{orders.length ? <div className="admin-data-table"><div className="table-head"><span>Order</span><span>Customer</span><span>Status</span><span>Total</span></div>{orders.map((o) => <Link to={`/orders/${o.id}`} key={o.id}><span>{o.id}</span><span>{o.userEmail}</span><span>{o.status}</span><b>${o.total}</b></Link>)}</div> : <p>No orders yet.</p>}</section></>}</AdminShell>;
}

export function AdminProducts({ products, reloadProducts }) {
  const [error, setError] = useState(''); const [q, setQ] = useState(''); const [busyId, setBusyId] = useState('');
  const list = useMemo(() => products.filter((p) => `${p.name} ${p.category} ${p.type}`.toLowerCase().includes(q.toLowerCase())), [products, q]);
  const remove = async (p) => { if (!window.confirm(`Delete ${p.name}?`)) return; setBusyId(p.id); setError(''); try { await api.deleteProduct(p.id); await reloadProducts(); } catch (e) { setError(e.message); } finally { setBusyId(''); } };
  return <AdminShell title="Products" actions={<Link className="primary-btn" to="/admin/products/new">Add product</Link>}><div className="admin-toolbar"><input placeholder="Search inventory" value={q} onChange={(e) => setQ(e.target.value)} /><span>{list.length} products</span></div>{error && <p className="auth-error">{error}</p>}<div className="admin-products-grid">{list.map((p) => <article key={p.id}><img src={p.image} alt={p.name} /><div><small>{p.category} · {p.type}</small><h3>{p.name}</h3><p>${p.price} · {p.stock} in stock</p></div><div className="admin-row-actions"><Link className="outline-btn" to={`/admin/products/${p.id}/edit`}>Edit</Link><button className="danger-btn" disabled={busyId === p.id} onClick={() => remove(p)}>{busyId === p.id ? 'Deleting…' : 'Delete'}</button></div></article>)}</div></AdminShell>;
}

const blank = { name: '', id: '', category: 'Women', type: 'Outerwear', price: 120, stock: 10, rating: 4.8, badge: '', color: 'Black', hex: '#171717', image: '', galleryText: '', sizesText: 'XS, S, M, L, XL', colorsText: 'Black:#171717', description: 'A refined VELORA essential crafted for everyday versatility.', material: 'Premium responsibly sourced blend.', care: 'Follow the garment care label.', featured: false };

export function AdminProductForm({ products, reloadProducts }) {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id);
  const source = products.find((p) => p.id === id);
  const [form, setForm] = useState(blank); const [status, setStatus] = useState({ busy: false, error: '' });
  useEffect(() => { if (!editing || !source) return setForm(blank); setForm({ ...source, galleryText: (source.gallery || []).join('\n'), sizesText: (source.sizes || []).join(', '), colorsText: (source.colors || []).map((c) => `${c.name}:${c.hex}`).join(', ') }); }, [id, source]);
  const change = (e) => { const { name, type, checked, value } = e.target; setForm((f) => ({ ...f, [name]: type === 'checkbox' ? checked : value })); };
  const submit = async (e) => { e.preventDefault(); setStatus({ busy: true, error: '' }); try { const payload = { ...form, price: Number(form.price), stock: Number(form.stock), rating: Number(form.rating), gallery: form.galleryText.split('\n').map((x) => x.trim()).filter(Boolean), sizes: form.sizesText.split(',').map((x) => x.trim()).filter(Boolean), colors: form.colorsText.split(',').map((x) => x.trim()).filter(Boolean).map((x) => { const [name, hex = '#171717'] = x.split(':'); return { name: name.trim(), hex: hex.trim() }; }) }; delete payload.galleryText; delete payload.sizesText; delete payload.colorsText; if (!payload.image && payload.gallery[0]) payload.image = payload.gallery[0]; if (editing) await api.updateProduct(id, payload); else await api.createProduct(payload); await reloadProducts(); navigate('/admin/products'); } catch (err) { setStatus({ busy: false, error: err.message }); } };
  return <AdminShell title={editing ? 'Edit product' : 'New product'}><form className="admin-form" onSubmit={submit}>{status.error && <p className="auth-error full">{status.error}</p>}<label>Name<input required name="name" value={form.name} onChange={change} /></label><label>Slug<input name="id" value={form.id} onChange={change} placeholder="auto-created from name" disabled={editing} /></label><label>Category<select name="category" value={form.category} onChange={change}><option>Women</option><option>Men</option><option>Accessories</option></select></label><label>Type<input required name="type" value={form.type} onChange={change} /></label><label>Price ($)<input required min="0" step="1" type="number" name="price" value={form.price} onChange={change} /></label><label>Stock<input required min="0" type="number" name="stock" value={form.stock} onChange={change} /></label><label>Rating<input min="1" max="5" step="0.1" type="number" name="rating" value={form.rating} onChange={change} /></label><label>Badge<input name="badge" value={form.badge || ''} onChange={change} placeholder="New / Bestseller" /></label><label>Primary colour<input name="color" value={form.color} onChange={change} /></label><label>Colour hex<input name="hex" value={form.hex || ''} onChange={change} /></label><label className="full">Primary image URL<input required name="image" value={form.image} onChange={change} /></label><label className="full">Gallery image URLs · one per line<textarea rows="5" name="galleryText" value={form.galleryText} onChange={change} /></label><label className="full">Sizes · comma separated<input name="sizesText" value={form.sizesText} onChange={change} /></label><label className="full">Colours · Name:#hex, comma separated<input name="colorsText" value={form.colorsText} onChange={change} /></label><label className="full">Description<textarea rows="3" name="description" value={form.description} onChange={change} /></label><label className="full">Materials<input name="material" value={form.material} onChange={change} /></label><label className="full">Care<input name="care" value={form.care} onChange={change} /></label><label className="checkbox-row full"><input type="checkbox" name="featured" checked={Boolean(form.featured)} onChange={change} /> Featured product</label><div className="admin-form-actions full"><Link className="outline-btn" to="/admin/products">Cancel</Link><button className="primary-btn" disabled={status.busy}>{status.busy ? 'Saving…' : editing ? 'Save changes' : 'Create product'}</button></div></form></AdminShell>;
}

export function AdminOrders() {
  const [orders, setOrders] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = () => api.adminOrders().then(setOrders).catch((e) => setError(e.message)); useEffect(load, []);
  const update = async (id, status) => { setBusy(id); try { const changed = await api.updateOrderStatus(id, status); setOrders((list) => list.map((o) => o.id === id ? changed : o)); } catch (e) { setError(e.message); } finally { setBusy(''); } };
  return <AdminShell title="Orders">{error && <p className="auth-error">{error}</p>}<div className="admin-data-table admin-orders"><div className="table-head"><span>Order</span><span>Customer</span><span>Status</span><span>Total</span></div>{orders.map((o) => <div key={o.id}><Link to={`/orders/${o.id}`}>{o.id}</Link><span>{o.userEmail}</span><select disabled={busy === o.id} value={o.status} onChange={(e) => update(o.id, e.target.value)}><option>Processing</option><option>Packed</option><option>Shipped</option><option>Delivered</option><option>Cancelled</option></select><b>${o.total}</b></div>)}</div></AdminShell>;
}

export function AdminCustomers() {
  const [users, setUsers] = useState([]); const [error, setError] = useState(''); useEffect(() => { api.adminUsers().then(setUsers).catch((e) => setError(e.message)); }, []);
  return <AdminShell title="Customers">{error && <p className="auth-error">{error}</p>}<div className="admin-data-table customers"><div className="table-head"><span>Name</span><span>Email</span><span>Country</span><span>Joined</span></div>{users.map((u) => <div key={u.id}><b>{u.name}</b><span>{u.email}</span><span>{u.country}</span><span>{u.createdAt ? new Date(u.createdAt).toLocaleDateString() : '—'}</span></div>)}</div></AdminShell>;
}

export function AdminMessages() {
  const [messages, setMessages] = useState([]); const [error, setError] = useState(''); useEffect(() => { api.adminMessages().then(setMessages).catch((e) => setError(e.message)); }, []);
  return <AdminShell title="Client messages">{error && <p className="auth-error">{error}</p>}<div className="message-grid">{messages.length ? messages.map((m, i) => <article key={m._id || m.id || i}><small>{m.topic || 'Enquiry'}</small><h3>{m.name}</h3><a href={`mailto:${m.email}`}>{m.email}</a><p>{m.message}</p><time>{m.createdAt ? new Date(m.createdAt).toLocaleString() : ''}</time></article>) : <p>No messages yet.</p>}</div></AdminShell>;
}
