import { Link } from 'react-router-dom';

const content = {
  about: { title:'About VELORA', lead:'We design a quieter kind of luxury. VELORA is an independent fashion concept focused on refined silhouettes, tactile materials and long-term wear.', cards:[['01','Form before noise','A wardrobe shaped by proportion, utility and restraint.'],['02','Material intelligence','We select fabrics for touch, drape, durability and how they age.'],['03','Everyday permanence','Pieces are designed to live beyond a single season.']] },
  collections: { title:'Seasonal Collections', lead:'Four stories built around proportion, texture and restraint.', cards:[['AUTUMN FORM','Soft structure','Warm neutrals, precise layers and fluid tailoring.'],['CITY TAILORING','Modern uniform','Architectural outerwear and disciplined trousers.'],['EVENING OBJECTS','After dark','Velvet, silk and sculptural accessories for evening.']] },
  journal: { title:'The Journal', lead:'Stories on style, materials, makers and the architecture of everyday dressing.', cards:[['ISSUE 08','The architecture of a coat','Why structure, balance and movement matter in outerwear.'],['ISSUE 07','A study in black','Texture makes monochrome dressing feel dimensional.'],['ISSUE 06','Objects that remain','The case for fewer, better accessories.']] },
  sustainability: { title:'Responsibility', lead:'We favour considered production, lower-volume collections, durable materials and packaging designed to reduce unnecessary waste.', cards:[['MATERIALS','Preferred fibres','We prioritise traceable natural fibres and recycled inputs where performance allows.'],['PRODUCTION','Smaller runs','Lower-volume releases help reduce excess inventory and unnecessary markdowns.'],['PACKAGING','Less material','Orders use recyclable paper-based packaging wherever possible.']] },
  shipping: { title:'Shipping & Delivery', lead:'Orders are prepared within 1–2 business days. Complimentary standard delivery is available on orders over $150.', cards:[['STANDARD','3–6 business days','$12 or complimentary over $150.'],['EXPRESS','1–3 business days','Calculated at checkout when available.'],['TRACKING','From dispatch','A tracking reference appears in your order history.']] },
  returns: { title:'Returns & Exchanges', lead:'Return unworn items with original tags within 30 days. Final-sale items are excluded.', cards:[['01','Start your return','Contact Client Services with your order number.'],['02','Prepare the item','Use original packaging and keep all garment tags attached.'],['03','Refund review','Approved returns are refunded to the original payment method.']] },
  faq: { title:'Frequently Asked Questions', lead:'Quick answers about orders, payments, sizing, delivery and returns.', cards:[['CAN I CHANGE AN ORDER?','Before dispatch','Contact us quickly and we will help when the order has not yet been packed.'],['HOW DO I CHOOSE A SIZE?','Use the guide','Compare your measurements and check the product fit notes.'],['IS PAYMENT SECURE?','Yes','The portfolio includes demo checkout and an optional Stripe test-mode integration.']] },
  privacy: { title:'Privacy Policy', lead:'We use personal information only to provide, improve and secure the shopping experience.', cards:[['ACCOUNT DATA','Profile & orders','Used to authenticate your account and display order history.'],['SERVICE DATA','Messages','Contact requests are stored so Client Services can reply.'],['PAYMENTS','No raw cards','VELORA does not store full card numbers in the application database.']] },
  terms: { title:'Terms & Conditions', lead:'This portfolio storefront demonstrates a commercial e-commerce experience. Product and transaction details are illustrative.', cards:[['DEMO STORE','Portfolio purpose','No physical products are shipped from this demonstration.'],['CONTENT','Project assets','Brand copy and catalogue data are created for the VELORA concept.'],['PAYMENT','Test mode','Use only published Stripe test cards when test mode is enabled.']] },
};

const sizes = [
  ['XS','80–84','62–66','86–90'],['S','85–89','67–71','91–95'],['M','90–94','72–76','96–100'],['L','95–100','77–82','101–106'],['XL','101–106','83–88','107–112'],
];

export default function InfoPage({ type }) {
  if (type === 'size') return <main className="info-page"><div className="eyebrow">VELORA FIT GUIDE</div><h1>Size Guide</h1><p>Measurements are body measurements in centimetres. For a relaxed fit, select the larger size when you fall between two sizes.</p><div className="size-table"><div><b>Size</b><b>Bust / Chest</b><b>Waist</b><b>Hip</b></div>{sizes.map((r) => <div key={r[0]}>{r.map((c) => <span key={c}>{c}</span>)}</div>)}</div><div className="info-grid"><article><span>FIT NOTE</span><h3>Tailoring</h3><p>Choose your usual size for a clean fit, or size up for an intentionally relaxed silhouette.</p></article><article><span>FOOTWEAR</span><h3>European sizing</h3><p>Shoes use EU sizing. If between sizes, we recommend choosing the larger size.</p></article><article><span>NEED HELP?</span><h3>Client Services</h3><p>Send your measurements through our contact page for personal sizing guidance.</p></article></div><Link className="text-link" to="/contact">Ask about sizing →</Link></main>;
  const page = content[type] || content.about;
  return <main className="info-page"><div className="eyebrow">VELORA ATELIER</div><h1>{page.title}</h1><p>{page.lead}</p><div className="info-grid">{page.cards.map(([n,h,p]) => <article key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p></article>)}</div><Link className="text-link" to="/shop">Explore the collection →</Link></main>;
}
