import { Minus, Plus, ShoppingBag, Trash2, X } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function CartDrawer({ open, close, cart, setCart }) {
  const update = (idx, delta) => setCart((items) => items.map((i, n) => n === idx ? { ...i, qty: Math.max(0, Math.min(10, i.qty + delta)) } : i).filter((i) => i.qty > 0));
  const remove = (idx) => setCart((items) => items.filter((_, n) => n !== idx));
  const total = cart.reduce((n, i) => n + i.price * i.qty, 0);
  return <div className={`drawer-wrap ${open ? 'open' : ''}`}><div className="scrim" onClick={close}/><aside className="drawer"><div className="drawer-head"><div><small>YOUR SELECTION</small><h2>Shopping bag <span>({cart.reduce((n, i) => n + i.qty, 0)})</span></h2></div><button className="icon" onClick={close} aria-label="Close bag"><X /></button></div><div className="drawer-body">{!cart.length ? <div className="empty"><ShoppingBag/><h3>Your bag is waiting</h3><p>Discover pieces designed to become signatures.</p><Link className="primary-btn" to="/shop" onClick={close}>Explore collection</Link></div> : cart.map((item, idx) => <div className="cart-item" key={`${item.id}-${item.size}-${item.color}`}><img src={item.image} alt={item.name}/><div><h4>{item.name}</h4><p>{item.color} · Size {item.size}</p><div className="qty"><button onClick={() => update(idx, -1)}><Minus/></button><span>{item.qty}</span><button onClick={() => update(idx, 1)}><Plus/></button></div><button className="drawer-remove" onClick={() => remove(idx)}><Trash2/> Remove</button></div><b>${item.price * item.qty}</b></div>)}</div>{!!cart.length && <div className="drawer-foot"><div><span>Subtotal</span><strong>${total}</strong></div><p>{total >= 150 ? 'Complimentary delivery unlocked.' : `$${150-total} away from complimentary delivery.`}</p><Link className="primary-btn drawer-checkout" to="/checkout" onClick={close}>Secure checkout</Link><Link className="drawer-view-bag" to="/cart" onClick={close}>View shopping bag</Link></div>}</aside></div>;
}
